### ISSUE TITLE
Can't get the linker to use x64 target

### ISSUE THREAD

**Issue by Seldom-SE** [rust-mobile/xbuild#169] opened 2024-02-23 21:12 UTC
Despite setting the architecture
`x build --device adb:emulator-5554 --arch x64`
it still tries to use `aarch64-linux-android`
```
info: component 'rust-std' for target 'aarch64-linux-android' is up to date
// ...
error: linking with `clang` failed: exit status: 1
  |
// ...
  = note: ld.lld: error: /home/seldom/.cache/x/Android.ndk/usr/lib/x86_64-linux-android/33/crtbegin_so.o is incompatible with aarch64linux
          ld.lld: error: /tmp/rustcPsKtaN/symbols.o is incompatible with aarch64linux
          ld.lld: error: /home/seldom/elevated_arcanum/target/x/debug/android/x64/cargo/x86_64-linux-android/debug/deps/bevy_mobile_example.10igtzs7ksk7cz79.rcgu.o is incompatible with aarch64linux
          ld.lld: error: /home/seldom/elevated_arcanum/target/x/debug/android/x64/cargo/x86_64-linux-android/debug/deps/bevy_mobile_example.111d2uc2pxob9jnz.rcgu.o is incompatible with aarch64linux
          ld.lld: error: /home/seldom/elevated_arcanum/target/x/debug/android/x64/cargo/x86_64-linux-android/debug/deps/bevy_mobile_example.112h6ifimoncc7yw.rcgu.o is incompatible with aarch64linux
          ld.lld: error: /home/seldom/elevated_arcanum/target/x/debug/android/x64/cargo/x86_64-linux-android/debug/deps/bevy_mobile_example.11npk11elk3u1ey4.rcgu.o is incompatible with aarch64linux
          ld.lld: error: /home/seldom/elevated_arcanum/target/x/debug/android/x64/cargo/x86_64-linux-android/debug/deps/bevy_mobile_example.126hkn995b0mvt7y.rcgu.o is incompatible with aarch64linux
          ld.lld: error: /home/seldom/elevated_arcanum/target/x/debug/android/x64/cargo/x86_64-linux-android/debug/deps/bevy_mobile_example.12sqfvmnp9lyh4u9.rcgu.o is incompatible with aarch64linux
          ld.lld: error: /home/seldom/elevated_arcanum/target/x/debug/android/x64/cargo/x86_64-linux-android/debug/deps/bevy_mobile_example.1330uz87oy8dd6qk.rcgu.o is incompatible with aarch64linux
          ld.lld: error: /home/seldom/elevated_arcanum/target/x/debug/android/x64/cargo/x86_64-linux-android/debug/deps/bevy_mobile_example.1334295v68h8weef.rcgu.o is incompatible with aarch64linux
          ld.lld: error: /home/seldom/elevated_arcanum/target/x/debug/android/x64/cargo/x86_64-linux-android/debug/deps/bevy_mobile_example.157ud2cu8j8nuj4u.rcgu.o is incompatible with aarch64linux
          ld.lld: error: /home/seldom/elevated_arcanum/target/x/debug/android/x64/cargo/x86_64-linux-android/debug/deps/bevy_mobile_example.15v9srs6sau8tzi3.rcgu.o is incompatible with aarch64linux
          ld.lld: error: /home/seldom/elevated_arcanum/target/x/debug/android/x64/cargo/x86_64-linux-android/debug/deps/bevy_mobile_example.165nkn4bsqj9g3ec.rcgu.o is incompatible with aarch64linux
          ld.lld: error: /home/seldom/elevated_arcanum/target/x/debug/android/x64/cargo/x86_64-linux-android/debug/deps/bevy_mobile_example.16d02s1fmw4mtv0y.rcgu.o is incompatible with aarch64linux
          ld.lld: error: /home/seldom/elevated_arcanum/target/x/debug/android/x64/cargo/x86_64-linux-android/debug/deps/bevy_mobile_example.16pbc2vdc19xmpzr.rcgu.o is incompatible with aarch64linux
          ld.lld: error: /home/seldom/elevated_arcanum/target/x/debug/android/x64/cargo/x86_64-linux-android/debug/deps/bevy_mobile_example.177osnsyympzikvr.rcgu.o is incompatible with aarch64linux
          ld.lld: error: /home/seldom/elevated_arcanum/target/x/debug/android/x64/cargo/x86_64-linux-android/debug/deps/bevy_mobile_example.1803giu0je8xf0gb.rcgu.o is incompatible with aarch64linux
          ld.lld: error: /home/seldom/elevated_arcanum/target/x/debug/android/x64/cargo/x86_64-linux-android/debug/deps/bevy_mobile_example.18cqz6on7whqbppg.rcgu.o is incompatible with aarch64linux
          ld.lld: error: /home/seldom/elevated_arcanum/target/x/debug/android/x64/cargo/x86_64-linux-android/debug/deps/bevy_mobile_example.18wwnqv21sy50p64.rcgu.o is incompatible with aarch64linux
          ld.lld: error: /home/seldom/elevated_arcanum/target/x/debug/android/x64/cargo/x86_64-linux-android/debug/deps/bevy_mobile_example.19dityh3rb2v9e35.rcgu.o is incompatible with aarch64linux
          ld.lld: error: too many errors emitted, stopping now (use --error-limit=0 to see all errors)
          clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```
(the emulator is x64)
![image](https://github.com/rust-mobile/xbuild/assets/38388947/0982b403-4647-43c3-a2ee-7978120de3f0)

**Comment by Seldom-SE** [comment] 2024-03-01 20:53
Also reproed on Windows
```
PS C:\Users\Hayde\Documents\Projects\elevated_arcanum> x run --device adb:emulator-5554
[1/3] Fetch precompiled artifacts
info: component 'rust-std' for target 'aarch64-linux-android' is up to date
[1/3] Fetch precompiled artifacts [162ms]
[2/3] Build rust `arcana_elevated`
   Compiling arcana_elevated v0.1.0 (C:\Users\Hayde\Documents\Projects\elevated_arcanum)
// ...
error: linking with `clang` failed: exit code: 1
  |
// ...
  = note: ld.lld: error: C:\\Users\\Hayde\\AppData\\Local\\x\\Android.ndk\\usr\\lib\\x86_64-linux-android\\33\\crtbegin_so.o is incompatible with aarch64linux
          ld.lld: error: C:\\Users\\Hayde\\AppData\\Local\\Temp\\rustcaeSn3Q\\symbols.o is incompatible with aarch64linux
          ld.lld: error: C:\\Users\\Hayde\\Documents\\Projects\\elevated_arcanum\\target\\x\\debug\\android\\x64\\cargo\\x86_64-linux-android\\debug\\deps\\bevy_mobile_example.102f1kqaxbam3hot.rcgu.o is incompatible with aarch64linux
          ld.lld: error: C:\\Users\\Hayde\\Documents\\Projects\\elevated_arcanum\\target\\x\\debug\\android\\x64\\cargo\\x86_64-linux-android\\debug\\deps\\bevy_mobile_example.10jrwzw3oy02hsvv.rcgu.o is incompatible with aarch64linux
          ld.lld: error: C:\\Users\\Hayde\\Documents\\Projects\\elevated_arcanum\\target\\x\\debug\\android\\x64\\cargo\\x86_64-linux-android\\debug\\deps\\bevy_mobile_example.10y091wnc1i6p80h.rcgu.o is incompatible with aarch64linux
          ld.lld: error: C:\\Users\\Hayde\\Documents\\Projects\\elevated_arcanum\\target\\x\\debug\\android\\x64\\cargo\\x86_64-linux-android\\debug\\deps\\bevy_mobile_example.12ol8g2ihbh7t0hu.rcgu.o is incompatible with aarch64linux
          ld.lld: error: C:\\Users\\Hayde\\Documents\\Projects\\elevated_arcanum\\target\\x\\debug\\android\\x64\\cargo\\x86_64-linux-android\\debug\\deps\\bevy_mobile_example.13ctc1o7940nyye6.rcgu.o is incompatible with aarch64linux
          ld.lld: error: C:\\Users\\Hayde\\Documents\\Projects\\elevated_arcanum\\target\\x\\debug\\android\\x64\\cargo\\x86_64-linux-android\\debug\\deps\\bevy_mobile_example.14lmfafd6l1c5wn8.rcgu.o is incompatible with aarch64linux
          ld.lld: error: C:\\Users\\Hayde\\Documents\\Projects\\elevated_arcanum\\target\\x\\debug\\android\\x64\\cargo\\x86_64-linux-android\\debug\\deps\\bevy_mobile_example.15ej1cs6o9qncrib.rcgu.o is incompatible with aarch64linux
          ld.lld: error: C:\\Users\\Hayde\\Documents\\Projects\\elevated_arcanum\\target\\x\\debug\\android\\x64\\cargo\\x86_64-linux-android\\debug\\deps\\bevy_mobile_example.1643hg2z520o04pj.rcgu.o is incompatible with aarch64linux
          ld.lld: error: C:\\Users\\Hayde\\Documents\\Projects\\elevated_arcanum\\target\\x\\debug\\android\\x64\\cargo\\x86_64-linux-android\\debug\\deps\\bevy_mobile_example.16fhjf6x3h5eavda.rcgu.o is incompatible with aarch64linux
          ld.lld: error: C:\\Users\\Hayde\\Documents\\Projects\\elevated_arcanum\\target\\x\\debug\\android\\x64\\cargo\\x86_64-linux-android\\debug\\deps\\bevy_mobile_example.16nkwkuzna4q57dy.rcgu.o is incompatible with aarch64linux
          ld.lld: error: C:\\Users\\Hayde\\Documents\\Projects\\elevated_arcanum\\target\\x\\debug\\android\\x64\\cargo\\x86_64-linux-android\\debug\\deps\\bevy_mobile_example.170aqede3tf0oj28.rcgu.o is incompatible with aarch64linux
          ld.lld: error: C:\\Users\\Hayde\\Documents\\Projects\\elevated_arcanum\\target\\x\\debug\\android\\x64\\cargo\\x86_64-linux-android\\debug\\deps\\bevy_mobile_example.170cel0x4wpnq8oc.rcgu.o is incompatible with aarch64linux
          ld.lld: error: C:\\Users\\Hayde\\Documents\\Projects\\elevated_arcanum\\target\\x\\debug\\android\\x64\\cargo\\x86_64-linux-android\\debug\\deps\\bevy_mobile_example.177stf62jgj652ve.rcgu.o is incompatible with aarch64linux
          ld.lld: error: C:\\Users\\Hayde\\Documents\\Projects\\elevated_arcanum\\target\\x\\debug\\android\\x64\\cargo\\x86_64-linux-android\\debug\\deps\\bevy_mobile_example.17h0zk80duflcc04.rcgu.o is incompatible with aarch64linux
          ld.lld: error: C:\\Users\\Hayde\\Documents\\Projects\\elevated_arcanum\\target\\x\\debug\\android\\x64\\cargo\\x86_64-linux-android\\debug\\deps\\bevy_mobile_example.185p5blwg2opufvl.rcgu.o is incompatible with aarch64linux
          ld.lld: error: C:\\Users\\Hayde\\Documents\\Projects\\elevated_arcanum\\target\\x\\debug\\android\\x64\\cargo\\x86_64-linux-android\\debug\\deps\\bevy_mobile_example.18nhhw06jmivhidm.rcgu.o is incompatible with aarch64linux
          ld.lld: error: C:\\Users\\Hayde\\Documents\\Projects\\elevated_arcanum\\target\\x\\debug\\android\\x64\\cargo\\x86_64-linux-android\\debug\\deps\\bevy_mobile_example.18okoiijv6bcb7qn.rcgu.o is incompatible with aarch64linux
          ld.lld: error: C:\\Users\\Hayde\\Documents\\Projects\\elevated_arcanum\\target\\x\\debug\\android\\x64\\cargo\\x86_64-linux-android\\debug\\deps\\bevy_mobile_example.191l3fv3fihcdb69.rcgu.o is incompatible with aarch64linux
          ld.lld: error: too many errors emitted, stopping now (use --error-limit=0 to see all errors)
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by MarijnS95** [comment] 2024-05-06 10:26
@Seldom-SE you're likely running into https://github.com/rust-mobile/xbuild/pull/127, which was already fixed and merged. Feel free to install from `git` for the time being (`cargo install --git https://github.com/rust-mobile/xbuild`) until we publish a new version containing this fix to crates.io.

**Comment by MarijnS95** [comment] 2024-05-06 10:26
In that sense this is also a duplicate of #126.

**Closed by MarijnS95** 2024-05-06 10:26 UTC
