### ISSUE TITLE
unrecognized abi armeabi-v7a

### ISSUE THREAD

**Issue by Gibbz** [rust-mobile/xbuild#182] opened 2024-07-27 14:23 UTC
Ive just tried to get my app running on my older LGv500 tablet. I get the error
```unrecognized abi armeabi-v7a```

Is this device to old to use with xbuild?

**Comment by pasimko** [comment] 2024-12-22 23:30
looks like https://github.com/rust-mobile/xbuild/pull/199 will address this

**Comment by MarijnS95** [comment] 2024-12-23 08:43
Closing as duplicate of #114, which is tracking both 32-bit ARM and x86 architectures.

**Closed by MarijnS95** 2024-12-23 08:43 UTC
